### ISSUE TITLE
download archmate iso

### ISSUE THREAD

**Issue by miftanurfarid** [mekatronik-achmadi/archmate#1]
gimana caranya download archmate iso-nya om?

**Comment by mekatronik-achmadi** [comment]
# ISO Download

There are two ISO variants, both can be downloaded from [SourceForge](https://sourceforge.net/projects/archlinux-custom-iso/files/archmate/)

The Mate Desktop variant:

![archmate](https://github.com/mekatronik-achmadi/archmate/assets/6890795/534cf95d-56ae-474e-b9ca-7cc0076abe33)

And the CLI/Openbox variant:

![archtmux](https://github.com/mekatronik-achmadi/archmate/assets/6890795/07aadcae-5da7-45ee-b4ad-6e0c29dd93f2)

![archob](https://github.com/mekatronik-achmadi/archmate/assets/6890795/2d788604-014b-4286-b2b9-39b463a54c2f)

# Build Your Own

If you have free time, you might interested build your own. I've written some [guideline](https://github.com/mekatronik-achmadi/archmate/blob/main/archiso/readme.md#build-yourself)

**Comment by miftanurfarid** [comment]
thank you.
